# Generated by Django 4.0.5 on 2022-06-23 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='password',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='name',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='password',
        ),
        migrations.RemoveField(
            model_name='students',
            name='email',
        ),
        migrations.RemoveField(
            model_name='students',
            name='name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='password',
        ),
    ]
